- web/src/AdapterPage.js
- web/src/AdapterTable.js
- web/src/PolicyTable.js
> Fixed Some Warning

- web/src/App.js
> fix target blank vulnerable issue

- web/src/EnforcerTable.js
- web/src/HomePage.js
- web/src/ModelTable.js
- web/src/PolicyTable.js
- web/src/index.css
This pr will close issue #40 and #41
> Refactor Table to fit full width available

- web/src/AdapterTable.js
- web/src/App.js
- web/src/EnforcerTable.js
- web/src/ModelTable.js
- web/src/Setting.js
1. fix #83  ,The warning(caused by the neglection of rowkey in tables) has been fixed.
2. The new row we add has been put onto the top of the tables for future management.
> Fixed warnings

- web/src/App.js
Changed RGB value of heart's color.
* [] - Backend work
* [] - Bug Fixes
> refactor: changed color from white to red

- .github/pull_request_template.md
Signed-off-by: Arteev Raina <arteevraina@gmail.com>
Just added an asterisk mark to make the checkboxes behave as possible.
* [] - Checked in IE11 and Firefox
* [] - Checked in mobile
* [] - Backend work
* [] - Frontend work
* [] - Bug Fixes
> fix: added asterisk mark for checkbox

- web/src/PolicyTable.js
Handled the case for the header being null.
Please Review this @hsluoyz :)
> fix: header is null

- web/src/EnforcerPage.js
Signed-off-by: Arteev Raina <arteevraina@gmail.com>
Explicitly handle the error for enforcer being null.
> fix: enforcer is null

- web/src/pages/Login.js
Signed-off-by: Arteev Raina <arteevraina@gmail.com>
> fix: hide credentials

- web/src/components/frame/Index.js
> UI: removed unwanted semicolons

- web/src/pages/Login.js
- web/src/pages/login.css
Signed-off-by: Arteev Raina <arteevraina@gmail.com>
Modified the UI of the Login Page.
> enhancement: Login Page

- web/src/components/frame/Index.js
- web/src/pages/dashboard/AdapterPage/AdapterTable.js
- web/src/pages/dashboard/EnforcerPage/EnforcerTable.js
- web/src/pages/dashboard/ModelPage/ModelTable.js
* Typo in dropdown list.
* Added Delete Icon.
> enhancements: changed Icons

- web/src/components/frame/Index.js
- web/src/components/frame/frame.css
Fixed a default  `min-width` for the web page.
> Fix the screen size

- web/src/pages/dashboard/AddPolicyList.js
Signed-off-by: Anurag Srivastava <anurag.as.srivastava@gmail.com>
Fixed a typo in AddPolicyList.js and formatted the file.
An error "Sava Failed" used to appear on form submission which now has been fixed to "Save Failed"
> Fixed typo AddPolicyList

- web/src/Setting.js
Reduced the time for which toast message is displayed.
```
else if (type === "success") {
message.success(text, 0.5);
} else if (type === "error") {
message.error(text, 0.5);
}
```
> fix: reduced time for toast message

- web/src/pages/dashboard/AdapterPage/AdapterTable.js
Changed Class-Based Component to Functional Component
> refactor: changed class to functional component

- web/src/App.js
- web/src/utils/auth.js
There was a small spelling error in the auth.js file in react js, I have corrected the spelling of the same and everywhere it was imported
> spelling error in auth.js file

- web/.eslintrc.js
- web/src/App.js
- web/src/PolicyTable.js
- web/src/pages/dashboard/Home.js
Cursor now changing to pointer when hover over avatar.
* [ ✔] - Tested Locally
* [✔] - Frontend work
* [✔ ] - Bug Fixes
* [ ✔] - Enhancements
> Fixed some typos and cursor fix.

- README.md
Signed-off-by: guxiaoyang_s20_307 <guxiaoyang@bupt.edu.cn>
Update the README about OAuth setup instructions for Casbin Dashboard. 
[reference.](https://github.com/casbin/casbin-forum#installation) 
[Refer to this comment.](https://github.com/casbin/casbin-dashboard/pull/129#issuecomment-729960393)
> Add more details about setting up OAuth application

- web/src/pages/dashboard/AddPolicyList.js
Solves the alignment issue on the submit button in the add policy page
> Aligning the submit button in the add policy page - (Solves - #125)

- web/src/pages/dashboard/AdapterPage/AddAdapter.js
- web/src/pages/dashboard/AdapterPage/EditAdapter.js
- web/src/pages/dashboard/AddPolicyList.js
- web/src/pages/dashboard/EditPolicyList.js
- web/src/pages/dashboard/EnforcerPage/AddEnforcer.js
- web/src/pages/dashboard/EnforcerPage/EditEnforcer.js
- web/src/pages/dashboard/ModelPage/AddModel.js
- web/src/pages/dashboard/ModelPage/EditModel.js
Aligning the submit button at the center of the page on each Add and Edit page like AddAdapter, EditEnforcer etc
Similar to #142 
It includes alignment of code issues as recommended by prettier js
> Center aligning the submit button for the add and edit page - (Solves - #143)
